apiVersion: v1
kind: Service
metadata:
  name: productcatalog-api-service
  namespace: productcatalog
  labels:
    app: productcatalog-api
spec:
  type: ClusterIP
  selector:
    app: productcatalog-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
